[package]
name = "rquickjs-playground"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "playground"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
llrt_abort = { git = "https://github.com/awslabs/llrt", branch = "main" }
llrt_buffer = { git = "https://github.com/awslabs/llrt", branch = "main" }
llrt_crypto = { git = "https://github.com/awslabs/llrt", branch = "main" }
llrt_events = { git = "https://github.com/awslabs/llrt", branch = "main" }
llrt_logging = { git = "https://github.com/awslabs/llrt", branch = "main" }
llrt_url = { git = "https://github.com/awslabs/llrt", branch = "main" }
llrt_util = { git = "https://github.com/awslabs/llrt", branch = "main" }
rquickjs = { version = "0.14", features = ["futures", "macro"] }
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }
uniffi = { version = "0.32.0", features = ["cli"] }

[target.'cfg(any(target_os = "ios", target_os = "android"))'.dependencies]
rquickjs = { version = "0.14", features = ["bindgen"] }
